#cloud-config

package_update: true
package_upgrade: true

runcmd:
  - git clone https://github.com/TamerOnLine/setup_peertube.git /root/setup_peertube
  - cd /root/setup_peertube
  - bash install_peertube.sh
