#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - |
    if [ ! -d "/root/setup_peertube" ]; then
      git clone https://github.com/TamerOnLine/setup_peertube.git /root/setup_peertube
    else
      cd /root/setup_peertube && git pull
    fi
  - cd /root/setup_peertube
  - bash install_peertube.sh
